name: 'CI'

on:
  release:
      types: [published]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      
      - name: 'Docker Build/Push'
        id: build
        uses: matootie/github-docker@v2.0.0
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          context: .ci
          imageName: bot
        
  
