name: 'CI'

on:
  release:
      types: [published]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout
      
      - name: 'Docker Build/Push'
        id: build
        uses: matootie/github-docker@v2.0.0
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          context: .ci
          imageName: zeroxsix
          
      - name: Notify
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }} 
        with:
          args: 'Sucessfully built and pushed 0x626f74, version ${{ GITHUB_REF}} to GitHub Registry: ${{ steps.build.outputs.imageURL }}'
        
  
